substitutions:
  _MASTER_BRANCH: master
steps:
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t eu.gcr.io/$PROJECT_ID/graalvm-builder:$SHORT_SHA . && \
        if [ "$BRANCH_NAME" == "${_MASTER_BRANCH}" ]; then docker push eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA; else echo "Not master branch: skipping image push."; fi
