steps:
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - '-c'
      - |
        docker build -t eu.gcr.io/$PROJECT_ID/graalvm-builder:$SHORT_SHA . &&
        [[ "$BRANCH_NAME" == "${_MASTER_BRANCH}" ]] && docker push eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA || echo "Not master branch: skipping image push."
