steps:
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/graalvm-builder:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/graalvm-builder:$SHORT_SHA']