secrets:
  - kmsKeyName: projects/knowhub-new/locations/global/keyRings/build/cryptoKeys/mvn-repo
    secretEnv:
      GITHUB_REPO_TOKEN: CiQAMCvQs1kwZZtIcUdE1arH6xac0h30sptvOc/DN3qcZUw6XXMSVwBppKKBv1ql+nsI8STBMUIBFxhxtesppu+GUAaxI/xw4uOgJCl/zoVwBKyVrtMYioFhBz3u7OJ3AXbcjEhy+DQNJoqrpl2Mw8xixrg0dvsR5GypZk5XQA==
substitutions:
  _GRAALVM_HOME: /opt/graalvm-ce-19.1.1
  _MASTER_BRANCH: master
steps:
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/graalvm-builder:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/graalvm-builder:$SHORT_SHA']