# gcloud alpha builds triggers import --source .cloudbuild/trigger-pr.yaml
name: graalvm-builder-pr
description: Pull Request
filename: .cloudbuild/cloudbuild-pr.yaml
github:
  name: graalvm-builder
  owner: luca-poddigue
  pullRequest:
    branch: .*
ignoredFiles:
- .gitignore
- .cloudbuild/trigger-*.yaml
- '*.txt'
- '*.md'